easy_admin:
  entities:
    Utilisateur:
      class: App\Entity\Utilisateur
      controller: App\Controller\UtilisateurController
      Enchere:
        class: App\Entity\Enchere
        controller: App\Controller\EnchereController